# Generated by Django 3.2.8 on 2021-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='market_catagory',
            new_name='market_category',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
