# Generated by Django 3.2.8 on 2021-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0002_auto_20211010_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='asset_class',
            field=models.TextField(default='STOCK'),
        ),
    ]
